# Generated by Django 4.2.6 on 2023-12-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_order_delete_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.IntegerField(default=150),
        ),
    ]
